#!/bin/sh
# Regenerate checked-in Concurrent-C emits. cmake never runs this.
#   ./tools/gen.sh          # both
#   ./tools/gen.sh kernels  # span_kernels only
#   ./tools/gen.sh bin_par  # bin_par only
#
# --no-line: no absolute #line paths in the foreign/checked-in tree.
# Kernels: #pragma(@prelude) off + CC_PARSER_MODE host.h (inert in rlsw.h).
set -e
cd "$(dirname "$0")/../src/fill"
CCC="${CCC:-ccc}"
out=../../include/generated

# ccc may hoist the parser-only host include outside #ifdef CC_PARSER_MODE.
# Keep it gated: span_kernels.c is #included into rlsw.h for the real build.
sanitize_kernels() {
    f="$out/span_kernels.c"
    python3 - "$f" <<'PY'
import pathlib, re, sys
p = pathlib.Path(sys.argv[1])
text = p.read_text()
text = re.sub(
    r'(?m)^#include\s+"span_kernels_host\.h"\s*\n+',
    "",
    text,
)
text = re.sub(
    r"(?ms)^#ifdef CC_PARSER_MODE\s*.*?^#endif\s*",
    "#ifdef CC_PARSER_MODE\n#include \"span_kernels_host.h\"\n#endif\n\n",
    text,
    count=1,
)
if "#include \"span_kernels_host.h\"" not in text:
    text = re.sub(
        r"(/\* generated by Concurrent-C[^\n]*\*/\n+)",
        r"\1\n#ifdef CC_PARSER_MODE\n#include \"span_kernels_host.h\"\n#endif\n\n",
        text,
        count=1,
    )
p.write_text(text)
PY
}

gen_kernels() {
    "$CCC" --emit-c-only --no-runtime --no-cache --no-line --out-dir "$out" span_kernels.ccs
    sanitize_kernels
}

gen_bin_par() {
    "$CCC" --emit-c-only --no-runtime --no-cache --no-line --out-dir "$out" bin_par.ccs
}

case "${1:-all}" in
    all)     gen_kernels; gen_bin_par ;;
    kernels) gen_kernels ;;
    bin_par) gen_bin_par ;;
    *) echo "usage: $0 [all|kernels|bin_par]" >&2; exit 2 ;;
esac
